meminfo: If we allocate with lmalloc() we should free with lfree()
Since commit 74518b8b691c ("elflink: Make ELF the default object
format") we've been using lmalloc() with free() instead of lfree().
This bug was pointed out by the following build warnings,

meminfo.c: In function ‘dump_e820’:
meminfo.c:93:5: warning: implicit declaration of function ‘free’
meminfo.c:93:5: warning: incompatible implicit declaration of built-in function ‘free’
vesainfo.c: In function ‘print_modes’:
vesainfo.c:82:2: warning: implicit declaration of function ‘free’
vesainfo.c:82:2: warning: incompatible implicit declaration of built-in function ‘free’

Signed-off-by: Matt Fleming <matt.fleming@intel.com>