isohybrid: fix isohybrid.c compile
Make isohybrid.c compile on gcc 4.4 32 bit instead of producing the
following error,

	isohybrid.c: In function ‘lendian_64’:
	isohybrid.c:437: error: integer constant is too large for ‘long’ type

Cc: Matthew Garrett <mjg@redhat.com>
Cc: Michal Soltys <soltys@ziu.info>
Signed-off-by: Frediano Ziglio <frediano.ziglio@citrix.com>
Signed-off-by: Matt Fleming <matt.fleming@intel.com>