sys/fileread.c: Fix build warning from missing prototype
Include the appropriate header to fix the following warning,

sys/fileread.c: In function ‘__file_get_block’:
sys/fileread.c:45:5: warning: implicit declaration of function ‘pmapi_read_file’

Signed-off-by: Matt Fleming <matt.fleming@intel.com>