sys/vesa: Include screencpy.o in $LIBVESA_OBJS
commit 4b0851493dce ("sys/vesa: Modularise common vesa code")
accidentally removed screencpy.o from $LIBVESA_OBJS, which results in
an undefined reference to __vesacon_copy_to_screen when loading
vesamenu.c32.

Signed-off-by: Matt Fleming <matt.fleming@intel.com>