sys/open.c: Fix building warnings from missing prototype
Fix the following warning by including the appropriate header,

sys/open.c: In function ‘open’:
sys/open.c:67:5: warning: implicit declaration of function ‘open_file’

Signed-off-by: Matt Fleming <matt.fleming@intel.com>