syslinux/idle.c: Fix build warnings from missing prototypes
Include core.h to fix the following build warnings,

syslinux/idle.c: In function ‘syslinux_reset_idle’:
syslinux/idle.c:41:5: warning: implicit declaration of function ‘reset_idle’
syslinux/idle.c: In function ‘syslinux_idle’:
syslinux/idle.c:46:5: warning: implicit declaration of function ‘__idle’

Signed-off-by: Matt Fleming <matt.fleming@intel.com>