sys/fileclose.c: Fix build warning from missing prototype
Include fs.h to avoid the following warning,

sys/fileclose.c: In function ‘__file_close’:
sys/fileclose.c:42:2: warning: implicit declaration of function ‘close_file’

Signed-off-by: Matt Fleming <matt.fleming@intel.com>