pxe: Add PXELINUX-specific symbols to symbol whitelist
We need to allow PXELINUX to link with required symbols at runtime
otherwise, when executing prdhcp.c32, the user will be presented with
the following message,

  Error: An undefined symbol was referenced

Add pxe_call, dns_resolv and unload_pxe to the symbol whitelist.

Reported-by: Gene Cumm <gene.cumm@gmail.com>
Signed-off-by: Matt Fleming <matt.fleming@intel.com>