chain.c32: fixing implicit declaration of function ‘syslinux_force_text_mode’
When building chain.c32:

$ make chain.c32
gcc -Wp,-MT,chain.o,-MD,./..chain.o.d -std=gnu99 -m32 -fno-stack-protector -mregparm=3 -DREGPARM=3 -march=i386 -Os -W -Wall -march=i386 -fomit-frame-pointer -D__COM32__ -nostdinc -iwithprefix include -I../../com32/libutil/include -I../../com32/include -I../../com32/gplinclude -c -o chain.o chain.c
chain.c: In function ‘do_boot’:
chain.c:552: warning: implicit declaration of function ‘syslinux_force_text_mode’
ld -m elf_i386 -T ../../com32/lib/com32.ld -o chain.elf chain.o ../../com32/libutil/libutil_com.a ../../com32/gpllib/libcom32gpl.a ../../com32/lib/libcom32.a /usr/lib/gcc/i486-linux-gnu/4.4.1/libgcc.a
objcopy -O binary chain.elf chain.c32

The following was missing:
  #include <syslinux/video.h>

- Gert Hulselmans